In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[23, 5]

In [3]:
vocab_size = 80
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[4, 27],
 [38, 65],
 [29, 33],
 [21, 26, 69],
 [5, 43, 32],
 [53, 27],
 [65, 43, 47],
 [61, 65],
 [61, 62],
 [22, 22]]

In [4]:
max_length = len(max(encoded_reviews, key=len))
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 4 27  0]
 [38 65  0]
 [29 33  0]
 [21 26 69]
 [ 5 43 32]
 [53 27  0]
 [65 43 47]
 [61 65  0]
 [61 62  0]
 [22 22  0]]


In [5]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


2022-06-06 21:06:08.339015: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
X = padded_reviews
y = sentiment

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              320       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 333
Trainable params: 333
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=0)


In [9]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 142ms/step - loss: 0.6500 - accuracy: 0.9000


0.8999999761581421

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

80