In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/albert_en_preprocess/3"
encoder_url = "3"

In [3]:
albert_preprocess = hub.KerasLayer(preprocess_url)
albert_encoder = hub.KerasLayer(encoder_url)

2022-06-14 17:38:41.113138: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
# #create HUB layer and pas it to preprocess URL

def get_sentence_embeding(sentences):
    preprocessed_text = albert_preprocess(sentences)
    return albert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.09927633,  0.07590731, -0.9603176 , ...,  0.9806314 ,
         0.72893876, -0.12989907],
       [ 0.5648691 , -0.6246964 ,  0.23342405, ...,  0.65837985,
        -0.9986798 ,  0.64189744]], dtype=float32)>

In [8]:
#Get embeding vectors for few sample words. Compare them using cosine similarity

e = get_sentence_embeding([
    "banana", 
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)
# print(len(e))
# print(e)
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])

array([[0.2523769]], dtype=float32)